from __future__ import annotations

import time
from typing import TYPE_CHECKING, Any, Dict, List, Optional

from src.app.schemas.jobs import JobStatusResponse
from src.app.schemas.moderation import TextModerationResult, VisualModerationResult
from src.app.schemas.summarization import SummarizationResult
from src.app.services.ingestion_service import IngestionService
from src.app.services.job_store import JobStore
from src.app.services.media_service import MediaService
from src.app.services.moderation_service import ModerationService
from src.app.services.post_store import PostResultStore
from src.app.services.report_store import ReportStore
from src.app.services.summarization_service import SummarizationService
from src.app.services.transcription_service import TranscriptionService
from src.app.utils.stage_logger import StageTimer
from src.app.core.metrics import JOB_PROCESSING_TIME, JOB_FAILURES

if TYPE_CHECKING:
    from src.app.services.aggregation_service import AggregationService


async def _set_stage(
    job_store: JobStore,
    job_id: str,
    campaign_id: str,
    status: str,
    stage: str,
    error: Optional[str] = None,
) -> None:
    await job_store.set(
        JobStatusResponse(
            job_id=job_id,
            campaign_id=campaign_id,
            status=status,  # queued | processing | completed | failed
            stage=stage,
            error=error,
        )
    )


async def process_campaign(ctx, job_id: str, campaign_id: str, campaign_payload: Dict[str, Any]) -> dict:
    """
    ARQ job entrypoint.

    Args:
        ctx: injected dependencies from worker startup()
        job_id: generated by API
        campaign_id: path param
        campaign_payload: validated CampaignInput dumped to dict (contains posts, etc.)
    """
    # ---- START JOB TIMER ----
    job_start = time.perf_counter()
    job_store: JobStore = ctx["job_store"]
    report_store: ReportStore = ctx["report_store"]
    post_store: PostResultStore = ctx["post_store"]

    ingestion_svc: IngestionService = ctx["ingestion_service"]
    media_svc: MediaService = ctx["media_service"]
    transcription_svc: TranscriptionService = ctx["transcription_service"]
    moderation_svc: ModerationService = ctx["moderation_service"]
    summarization_svc: SummarizationService = ctx["summarization_service"]
    aggregation_svc: AggregationService = ctx["aggregation_service"]

    await _set_stage(job_store, job_id, campaign_id, status="running", stage="ingestion")

    try:
        posts_payload = campaign_payload.get("posts") or []
        ingestion_result = await ingestion_svc.ingest(campaign_id=campaign_id, posts_payload=posts_payload)
        
        # If ingest() returns a tuple, unpack it
        if isinstance(ingestion_result, tuple):
            posts, metadata = ingestion_result
            ingestion = type('obj', (object,), {'posts': posts, 'metadata': metadata})()
        else:
            ingestion = ingestion_result

        if not ingestion.posts:
            raise RuntimeError("No posts found in campaign payload")

        visual_results: List[VisualModerationResult] = []
        text_results: List[TextModerationResult] = []
        summaries: List[SummarizationResult] = []
        post_results: List[dict] = []

        total = len(ingestion.posts)

        for idx, post in enumerate(ingestion.posts, start=1):
            post_id = None
            per_post_error_stage = None
            per_post_error_message = None

            try:
                # IngestedPost is a model, not dict
                post_id = post.post_id
                caption = post.caption or ""

                # ---- MEDIA EXTRACTION STAGE ----
                await _set_stage(job_store, job_id, campaign_id, status="running", stage="media")

                timer = StageTimer(job_id, post_id, "media")
                try:
                    media_url = post.media_urls[0] if post.media_urls else post.url
                    media_result = await media_svc.prepare_post_media(
                        post_id=post_id,
                        media_url=media_url,
                        extract_audio_enabled=True,
                        sample_frames_enabled=True,
                    )

                    frame_paths = [
                        f.path if hasattr(f, "path") else str(f)
                        for f in (media_result.frames or [])
                    ]
                    audio_path = media_result.audio_path
                    timer.log(success=True, retry_count=0)
                except Exception as e:
                    per_post_error_stage = "media"
                    per_post_error_message = str(e)
                    timer.log(success=False, retry_count=0)
                    raise

                # ---- TRANSCRIPTION ----
                try:
                    await _set_stage(job_store, job_id, campaign_id, status="running", stage=f"post:{idx}/{total}:transcription")
                    timer = StageTimer(job_id, post_id, "transcription")

                    transcript_text = ""
                    if audio_path:
                        transcript_text = await transcription_svc.transcribe(post_id, audio_path)

                    timer.log(success=True, retry_count=0)
                except Exception as e:
                    per_post_error_stage = "transcription"
                    per_post_error_message = str(e)
                    timer.log(success=False, retry_count=0)
                    raise

                # ---- VISUAL MODERATION ----
                try:
                    await _set_stage(job_store, job_id, campaign_id, status="running", stage=f"post:{idx}/{total}:visual_moderation")
                    timer = StageTimer(job_id, post_id, "visual_moderation")

                    visual_result = await moderation_svc.moderate_visual(post_id, frame_paths)

                    timer.log(success=True, retry_count=0)
                except Exception as e:
                    per_post_error_stage = "visual_moderation"
                    per_post_error_message = str(e)
                    timer.log(success=False, retry_count=0)
                    raise

                # ---- TEXT MODERATION ----
                try:
                    await _set_stage(job_store, job_id, campaign_id, status="running", stage=f"post:{idx}/{total}:text_moderation")
                    timer = StageTimer(job_id, post_id, "text_moderation")

                    combined_text = (caption or "") + " " + (transcript_text or "")
                    text_result = await moderation_svc.moderate_text(post_id, combined_text)

                    timer.log(success=True, retry_count=0)
                except Exception as e:
                    per_post_error_stage = "text_moderation"
                    per_post_error_message = str(e)
                    timer.log(success=False, retry_count=0)
                    raise

                # ---- SUMMARIZATION ----
                await _set_stage(
                    job_store,
                    job_id,
                    campaign_id,
                    status="running",
                    stage=f"post:{idx}/{total}:summarization",
                )

                timer = StageTimer(job_id, post_id, "summarization")
                try:
                    sres = await summarization_svc.summarize(
                        post_id=post_id,
                        caption=caption,
                        transcript_text=transcript_text,
                        visual_findings={
                            "visual_categories": [
                                {"category": c.category, "score": c.safety_score, "status": c.status}
                                for c in visual_result.categories
                            ],
                            "visual_partial_failures": visual_result.partial_failures,
                        },
                    )
                    timer.log(success=True, retry_count=0)
                except Exception as e:
                    per_post_error_stage = "summarization"
                    per_post_error_message = str(e)
                    timer.log(success=False, retry_count=0)
                    raise

                visual_results.append(visual_result)
                text_results.append(text_result)
                summaries.append(sres)

                await post_store.set(
                    campaign_id,
                    post_id,
                    {
                        "success": True,
                        "post_id": post_id,
                        "caption": caption,
                        "media": {
                            "video_path": media_result.video_path,
                            "audio_path": media_result.audio_path,
                            "frames": [f.model_dump() for f in media_result.frames],
                        },
                        "visual": visual_result.model_dump(),
                        "text": text_result.model_dump(),
                        "summary": sres.model_dump(),
                    },
                )

                post_results.append(
                    {
                        "post_id": post_id,
                        "success": True,
                        "error_stage": None,
                        "error_message": None,
                    }
                )

            except Exception as e:
                if per_post_error_stage is None:
                    per_post_error_stage = "unknown"
                if per_post_error_message is None:
                    per_post_error_message = str(e)
                await post_store.set(
                    campaign_id,
                    post_id,
                    {
                        "success": False,
                        "post_id": post_id,
                        "error_stage": per_post_error_stage,
                        "error_message": per_post_error_message,
                    },
                )
                post_results.append(
                    {
                        "post_id": post_id,
                        "success": False,
                        "error_stage": per_post_error_stage,
                        "error_message": per_post_error_message,
                    }
                )
                continue

        # ---- AGGREGATION STAGE ----
        await _set_stage(job_store, job_id, campaign_id, status="running", stage="aggregation")

        timer = StageTimer(job_id, "campaign", "aggregation")
        try:
            report = aggregation_svc.aggregate(
                campaign_id=campaign_id,
                visual_results=visual_results,
                text_results=text_results,
                summaries=summaries,
                post_results=post_results,
            )
            timer.log(success=True, retry_count=0)
        except Exception:
            timer.log(success=False, retry_count=0)
            raise

        await report_store.set(report)

        await _set_stage(job_store, job_id, campaign_id, status="done", stage="done")

        # ---- RECORD JOB SUCCESS ----
        job_duration = time.perf_counter() - job_start
        JOB_PROCESSING_TIME.labels(stage="campaign").observe(job_duration)

        return {"ok": True, "job_id": job_id, "campaign_id": campaign_id, "duration_seconds": job_duration}

    except Exception as e:
        # ---- RECORD JOB FAILURE ----
        error_stage = getattr(e, "stage", "unknown")
        JOB_FAILURES.labels(error_stage=error_stage).inc()

        await _set_stage(job_store, job_id, campaign_id, status="failed", stage="error", error=str(e))
        raise