# src/app/workers/tasks.py
from __future__ import annotations

import time
from typing import Any, Dict, List, Optional

from src.app.schemas.jobs import JobStatusResponse
from src.app.schemas.moderation import TextModerationResult, VisualModerationResult
from src.app.schemas.summarization import SummarizationResult
from src.app.services.ingestion_service import IngestionService
from src.app.services.job_store import JobStore
from src.app.services.media_service import MediaService
from src.app.services.moderation_service import ModerationService
from src.app.services.post_store import PostResultStore
from src.app.services.report_store import ReportStore
from src.app.services.summarization_service import SummarizationService
from src.app.services.transcription_service import TranscriptionService
from src.app.utils.stage_logger import StageTimer
from src.app.core.metrics import JOB_PROCESSING_TIME, JOB_FAILURES


async def _set_stage(
    job_store: JobStore,
    job_id: str,
    campaign_id: str,
    status: str,
    stage: str,
    error: Optional[str] = None,
) -> None:
    await job_store.set(
        JobStatusResponse(
            job_id=job_id,
            campaign_id=campaign_id,
            status=status,  # queued | processing | completed | failed
            stage=stage,
            error=error,
        )
    )


async def process_campaign(ctx, job_id: str, campaign_id: str, campaign_payload: Dict[str, Any]) -> dict:
    """
    ARQ job entrypoint.

    Args:
        ctx: injected dependencies from worker startup()
        job_id: generated by API
        campaign_id: path param
        campaign_payload: validated CampaignInput dumped to dict (contains posts, etc.)
    """
    # ---- START JOB TIMER ----
    job_start = time.perf_counter()

    job_store: JobStore = ctx["job_store"]
    report_store: ReportStore = ctx["report_store"]
    post_store: PostResultStore = ctx["post_store"]

    ingestion_svc: IngestionService = ctx["ingestion_service"]
    media_svc: MediaService = ctx["media_service"]
    transcription_svc: TranscriptionService = ctx["transcription_service"]
    moderation_svc: ModerationService = ctx["moderation_service"]
    summarization_svc: SummarizationService = ctx["summarization_service"]

    await _set_stage(job_store, job_id, campaign_id, status="processing", stage="ingestion")

    try:
        posts_payload = campaign_payload.get("posts") or []
        ingestion = await ingestion_svc.ingest(campaign_id=campaign_id, posts_payload=posts_payload)

        if not ingestion.posts:
            raise RuntimeError("No posts found in campaign payload")

        visual_results: List[VisualModerationResult] = []
        text_results: List[TextModerationResult] = []
        summaries: List[SummarizationResult] = []
        post_results: List[dict] = []

        total = len(ingestion.posts)

        for idx, post in enumerate(ingestion.posts, start=1):
            post_id = post.post_id
            caption = post.caption or ""
            media_url = post.media_urls[0] if post.media_urls else None

            visual_result = None
            text_result = None
            summary_result = None

            post_partial_failure = False
            post_errors = []

            # --------------------
            # MEDIA
            # --------------------
            try:
                await _set_stage(
                    job_store,
                    job_id,
                    campaign_id,
                    status="processing",
                    stage=f"post:{idx}/{total}:media",
                )

                timer = StageTimer(job_id, post_id, "media")
                try:
                    media = await media_svc.prepare_post_media(
                        post_id=post_id,
                        media_url=str(media_url) if media_url else None,
                        extract_audio_enabled=True,
                        sample_frames_enabled=True,
                    )
                    timer.log(success=True, retry_count=0)
                except Exception:
                    timer.log(success=False, retry_count=0)
                    raise

            except Exception as e:
                # Media is fatal for post
                post_partial_failure = True
                post_errors.append(f"media_failed: {str(e)}")

                await post_store.set(
                    campaign_id,
                    post_id,
                    {
                        "success": False,
                        "partial_failure": True,
                        "errors": post_errors,
                    },
                )

                post_results.append(
                    {
                        "post_id": post_id,
                        "success": False,
                        "partial_failure": True,
                        "error_message": str(e),
                    }
                )
                continue

            # --------------------
            # VISUAL MODERATION
            # --------------------
            try:
                await _set_stage(
                    job_store,
                    job_id,
                    campaign_id,
                    status="processing",
                    stage=f"post:{idx}/{total}:visual_moderation",
                )

                timer = StageTimer(job_id, post_id, "visual_moderation")
                try:
                    visual_result = await moderation_svc.moderate_visual(
                        post_id=post_id,
                        frame_paths=[f.path for f in media.frames],
                    )
                    timer.log(success=True, retry_count=0)
                    visual_results.append(visual_result)
                except Exception:
                    timer.log(success=False, retry_count=0)
                    raise

            except Exception as e:
                post_partial_failure = True
                post_errors.append(f"visual_moderation_failed: {str(e)}")

            # --------------------
            # TRANSCRIPTION
            # --------------------
            transcript_text = ""
            try:
                if media.audio_path:
                    await _set_stage(
                        job_store,
                        job_id,
                        campaign_id,
                        status="processing",
                        stage=f"post:{idx}/{total}:transcription",
                    )

                    timer = StageTimer(job_id, post_id, "transcription")
                    try:
                        t = await transcription_svc.transcribe(
                            post_id=post_id,
                            audio_path=media.audio_path,
                        )
                        transcript_text = t.transcript_text
                        timer.log(success=True, retry_count=0)
                    except Exception:
                        timer.log(success=False, retry_count=0)
                        raise

            except Exception as e:
                post_partial_failure = True
                post_errors.append(f"transcription_failed: {str(e)}")

            # --------------------
            # TEXT MODERATION
            # --------------------
            try:
                await _set_stage(
                    job_store,
                    job_id,
                    campaign_id,
                    status="processing",
                    stage=f"post:{idx}/{total}:text_moderation",
                )

                timer = StageTimer(job_id, post_id, "text_moderation")
                try:
                    text_result = await moderation_svc.moderate_text(
                        post_id=post_id,
                        text=(caption + "\n" + transcript_text).strip(),
                        lang="en",
                    )
                    timer.log(success=True, retry_count=0)
                    text_results.append(text_result)
                except Exception:
                    timer.log(success=False, retry_count=0)
                    raise

            except Exception as e:
                post_partial_failure = True
                post_errors.append(f"text_moderation_failed: {str(e)}")

            # --------------------
            # SUMMARIZATION
            # --------------------
            try:
                await _set_stage(
                    job_store,
                    job_id,
                    campaign_id,
                    status="processing",
                    stage=f"post:{idx}/{total}:summarization",
                )

                timer = StageTimer(job_id, post_id, "summarization")
                try:
                    summary_result = await summarization_svc.summarize(
                        post_id=post_id,
                        caption=caption,
                        transcript_text=transcript_text,
                        visual_findings={
                            "visual_categories": [
                                {"category": c.category, "score": c.safety_score, "status": c.status}
                                for c in (visual_result.categories if visual_result else [])
                            ]
                        },
                    )
                    timer.log(success=True, retry_count=0)
                    summaries.append(summary_result)
                except Exception:
                    timer.log(success=False, retry_count=0)
                    raise

            except Exception as e:
                post_partial_failure = True
                post_errors.append(f"summarization_failed: {str(e)}")

            # --------------------
            # STORE POST RESULT
            # --------------------
            await post_store.set(
                campaign_id,
                post_id,
                {
                    "success": True,
                    "partial_failure": post_partial_failure,
                    "errors": post_errors,
                    "visual": visual_result.model_dump() if visual_result else None,
                    "text": text_result.model_dump() if text_result else None,
                    "summary": summary_result.model_dump() if summary_result else None,
                },
            )

            post_results.append(
                {
                    "post_id": post_id,
                    "success": True,
                    "partial_failure": post_partial_failure,
                    "error_message": "; ".join(post_errors) if post_errors else None,
                }
            )

        # ---- AGGREGATION STAGE ----
        await _set_stage(job_store, job_id, campaign_id, status="processing", stage="aggregation")

        timer = StageTimer(job_id, "campaign", "aggregation")
        try:
            report = aggregation_svc.aggregate(
                campaign_id=campaign_id,
                visual_results=visual_results,
                text_results=text_results,
                summaries=summaries,
                post_results=post_results,
            )
            timer.log(success=True, retry_count=0)
        except Exception:
            timer.log(success=False, retry_count=0)
            raise

        await report_store.set(report)

        await _set_stage(job_store, job_id, campaign_id, status="completed", stage="done")

        # ---- RECORD JOB SUCCESS ----
        job_duration = time.perf_counter() - job_start
        JOB_PROCESSING_TIME.labels(campaign_id=campaign_id).observe(job_duration)

        return {
            "ok": True,
            "job_id": job_id,
            "campaign_id": campaign_id,
            "duration_seconds": job_duration,
        }

    except Exception as e:
        # ---- RECORD JOB FAILURE ----
        error_stage = getattr(e, "stage", "unknown")
        JOB_FAILURES.labels(error_stage=error_stage).inc()

        await _set_stage(
            job_store,
            job_id,
            campaign_id,
            status="failed",
            stage="error",
            error=str(e),
        )
        raise